networks:
  default:
    driver: bridge

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host" #Uses host's ip 192.168.31.88
    environment:
      TZ: 'America/Toronto'
      WEBPASSWORD: ${PIHOLE_PWD}
      FTLCONF_REPLY_ADDR4: 192.168.31.88
      FTLCONF_RATE_LIMIT: 0/0
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  xray:
    image: teddysun/xray:latest
    container_name: xray-vless
    volumes:
      - ./xray:/etc/xray
    ports:
      - "10001:10001"
    restart: unless-stopped
    dns:
      - 192.168.31.88 # Host IP Address
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --protocol quic --token ${TUNNEL_TOKEN}

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - "3001:3001/tcp"
    dns:
      - 192.168.31.88 # Host IP Address 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
